trigger:
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git config user.name "Gabriel Souza"
    git config user.email "gabrielpaixao588@gmail.com"

    git remote set-url origin https://$(AZURE_DEVOPS_PAT)@dev.azure.com/BREUPX-ORG/Learn-Project/_git/Addin
    
    git remote -v
    
    git push origin --all
    git push origin --tags
  displayName: 'Mirror changes to Azure DevOps repository'
