trigger:
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git remote add azure https://$(AZURE_DEVOPS_PAT)G@dev.azure.com/BREUPX-ORG/Learn-Project/_git/Addin
    git add .
    git commit -m "Deploying changes from GitHub"
    git push azure main --force
  displayName: 'Mirror changes to Azure DevOps repository'
