trigger:
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git config user.name "Gabriel Paixão"
    git config user.email "gabrielpaixao588@gmail.com"

    # Adiciona o repositório remoto do Azure DevOps
    git remote set-url origin https://BREUPX-ORG@dev.azure.com/BREUPX-ORG/Learn-Project/_git/Addin
    
    git push origin --all
    git push origin --tags
  displayName: 'Mirror changes to Azure DevOps repository'
