trigger:
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - -'
      Write-Host 'Reflect GitHub repo changes to Azure DevOps repo'
      Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - - '
      
      $stageDir = '$(Build.SourcesDirectory)' | Split-Path
      $githubDir = $stageDir + "\" + "gitHub"
      $destination = $githubDir + "\" + "Addin.git"
      
      $alias = 'Gabrieups' + "$(Github.PAT)"
      $sourceURL = 'https://' + $alias + '@github.com/Gabrieups/Addin'
      
      $destURL = 'https://' + "$(AzureDevOps.PAT)@dev.azure.com/BREUPX-ORG/Learn-Project/_git/Addin"
      
      if ((Test-Path -path $githubDir)) {
          Remove-Item -Path $githubDir -Recurse -force
      }
      
      if (!(Test-Path -path $githubDir)) {
          New-Item -ItemType directory -Path $githubDir
          Set-Location $githubDir
          git clone --mirror $sourceURL
      } else {
          Write-Host "The given folder path $githubDir already exists";
      }
      
      Set-Location $destination
      Write-Output '*****Git removing remote secondary****'
      git remote rm secondary
      Write-Output '*****Git remote add****'
      git remote add --mirror=fetch secondary $destURL
      
      Write-Output '*****Git fetch origin****'
      git fetch $sourceURL
      Write-Output '*****Git push secondary****'
      git push secondary --all
      
      Write-Output '**GitHub repo synced with Azure DevOps repo**'
      
      Set-Location $stageDir
      if ((Test-Path -path $githubDir)) {
          Remove-Item -Path $githubDir -Recurse -force
      }
