trigger: none

pool:
  vmImage: windows-latest

jobs:
 - job: Build
   displayName: 'npm install and build'
   steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'

    - script: |
        npm install
    - script: |
        npm run build --if-present
        npm run test --if-present

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - script: |
        echo $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        artifactName: 'drop'
        publishLocation: 'Container'

 - job: Deploy
   displayName: Deploy 
   dependsOn: Build
   steps:
   
   - task: DownloadBuildArtifacts@1
     inputs:
       buildType: 'current'
       downloadType: 'single'
       artifactName: 'drop'
       downloadPath: '$(Build.ArtifactStagingDirectory)'
   - task: AzureRmWebAppDeployment@4
     inputs:
       ConnectionType: 'AzureRM'
       azureSubscription: 'SUBS-PX-TEST(0f3bc5f8-c245-4de5-87b6-e3c3943c3a8a)'
       appType: 'webApp'
       WebAppName: 'breu-app-testing'
       packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'