trigger:
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - -'
      Write-Host 'Refletir mudanças do repositório GitHub no repositório Azure DevOps'
      Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - - '

      $stageDir = '$(Build.SourcesDirectory)' | Split-Path
      $githubDir = $stageDir + "\" + "gitHub"
      $source = $githubDir + "\" + "Addin.git"

      $alias = 'Gabrieups' + "$(Github.PAT)"
      $sourceURL = 'https://' + $alias + '@github.com/Gabrieups/Addin'

      $dstinationURL = 'https://' + "$(AzureDevOps.PAT)@dev.azure.com/BREUPX-ORG/Learn-Project/_git/Addin"

      if ((Test-Path -path $githubDir)) {
          Remove-Item -Path $githubDir -Recurse -force
      }

      if (!(Test-Path -path $githubDir)) {
          New-Item -ItemType directory -Path $githubDir
          Set-Location $githubDir
          git clone --mirror $sourceURL
      } else {
          Write-Host "The given folder path $githubDir already exists";
      }

      Set-Location $source
      Write-Output '*****Git removing remote secondary****'
      git remote rm secondary
      Write-Output '*****Git remote add****'
      git remote add --mirror=fetch secondary $dstinationURL

      Write-Output '*****Git fetch origin****'
      git fetch origin

      Write-Output '*****Git pull secondary****'
      git pull secondary main  # Adiciona um pull para sincronizar com o Azure DevOps

      Write-Output '*****Git push secondary****'
      git push secondary --all --force  # Ou adicione `--force` se for seguro sobrescrever

      Write-Output '**GitHub repo synced with Azure DevOps repo**'

      Set-Location $stageDir
      if ((Test-Path -path $githubDir)) {
          Remove-Item -Path $githubDir -Recurse -force
      }

